### ISSUE TITLE
The check for the ISO in /root does not seem to work

### ISSUE THREAD

**Issue by bartmcleod** [PeterMosmans/ansible-role-virtualbox-guest#10]
When experimenting with the role I found it wasn't as easy to make the check for the ISO file pass.

The comment states it checks the host for the root path, but it only works if I use a path like /vagrant/ansible/vbox (on the guest). So either the comment is wrong (host should be guest) or the task might be wrong.

``` 
- name: Check if the ISO file is present on the guest
    stat: path=/vagrant/ansible/vbox/VBoxGuestAdditions.iso
    register: file_path
    ignore_errors: yes
```

It would be easier maybe to make the path configurable? Have an entry in group_vars and copy from there to /root on the guest?

**Comment by PeterMosmans** [comment]
Hi @bartmcleod , thanks for the feedback.
You're totally right, the *host* path should be configurable (personally I never use *auto*, but specify the version). Any suggestions / pull requests for path (names) are welcome 😉

**Comment by PeterMosmans** [comment]
Hi @bartmcleod - I implemented your suggestion. Thanks!
Should you have any other, please let me know.
