### ISSUE TITLE
Rewrite Ansible warning on the use of jinja2 parameters

### ISSUE THREAD

**Issue by PeterMosmans** [PeterMosmans/ansible-role-virtualbox-guest#12]
Version 2.3+ of Ansible complains on the use of '{{'

 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: vbox_guest_version.stdout != "{{
virtualbox_version }}"

TASK [PeterMosmans.virtualbox-guest : Check if the ISO file is present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Check if the CD is present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Check if CD or ISO file is present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Download ISO file when the requested version is not present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Re-check if the ISO file is present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Fail if CD or ISO file is still not present on the host] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Use correct ISO path (file or CD)] *******
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Check if VBoxGuest additions ISO is mounted] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Mount VBoxGuestAdditions] ****************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: mount_path is defined and "{{ mount_path.stdout
}}" == ""

TASK [PeterMosmans.virtualbox-guest : Check if VBoxGuest additions ISO is mounted] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Find out kernel version] *****************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Find out architecture-independent kernel name] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Save the current list of packages] *******
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Install necessary packages for compiling] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Install kernel headers] ******************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Check which packages were installed] *****
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Create a list of installed packages] *****
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Build and install x11 VBoxGuestAdditions from file] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Build and install VBoxGuestAdditions from file] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Unmount VBoxGuestAdditions] **************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Remove installed packages for compiling] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Remove build logfiles, artefacts and ISO files] ***
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

TASK [PeterMosmans.virtualbox-guest : Remove cdrom fstab entry] ****************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: (vbox_guest_version.stdout != "{{
virtualbox_version }}")

See https://github.com/ansible/ansible/issues/22397 and https://github.com/ansible/ansible/issues/22690 for more information and potential solutions

**Comment by wtli** [comment]
try: yum -y install python-devel 
i solve this problem

**Comment by PeterMosmans** [comment]
Hi @wtli - thanks for the hint. However, the warnings have to do with new (and deprecated) Ansible syntax. The angular brackets need to be removed in order to 'fix' the warning for Ansible 2.3+
