### ISSUE TITLE
idea: upgrade kernel before install virtualbox additions

### ISSUE THREAD

**Issue by fredleger** [PeterMosmans/ansible-role-virtualbox-guest#7]
Actually that won't work because of uname -r used to detect the kernel version. maybe switching to package manager to insure which kernel is installed ?

**Comment by PeterMosmans** [comment]
I had that happening to me as well once, the headers libs couldn't be installed as the machine needed a reboot (old kernel). Maybe we could add an error message stating what happens and why, so that the user can 'voluntarily' choose to reboot ?

**Comment by fredleger** [comment]
it wasn't something that arrived to me. just an idea of enhancement.

my idea was :
- offer a switch to force kernel upgrade before virtualbox additions compilation
- dont rely on uname -r to determine kernel version (which forced me to introduce a reboot). instead dig for the kernel version to target with the package manager

I don't know if this is easy, but could be nice. 
Because it's what you just want, latest kernel and latest additions compiled for this kernel :-)

**Comment by PeterMosmans** [comment]
Hi @fredleger - I implemented this idea into another role, `ansible-role-bootstrap`, which can optionally reboot the machine when the kernel has been changed, and continue. I'm not sure whether it is a good fit for this role, an automatic reboot. It can be done though....

**Comment by fredleger** [comment]
yes can be a way to go. Thxs
